[project]
name = "triplestore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alexios Zavras (zvr)", email = "zvr+git@zvr.gr" }
]
requires-python = ">=3.12"
dependencies = ["requests"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "mypy",
    "build"
]

[tool.pytest.ini_options]
pythonpath = ["src"]